story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
]

story6/urls.py
from django.urls import path
from . import views
from .views import Join1, Join2, dynamic_lookup_view

app_name = 'story6'

urlpatterns = [
    path('', Join2),
    path('<int:my_id>/', dynamic_lookup_view, name='daftar'),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    Aktivitas = models.CharField(max_length=100)
    
    def __str__(self):
        return self.Aktivitas

class Participant(models.Model):
    Peserta = models.CharField(max_length=50)
    Orang = models.ManyToManyField(Activity)
    def __str__(self):
        return self.Peserta

story6/forms.py
from django import forms

class PesertaForm(forms.Form):
    Peserta = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Masukkan nama',
        'type' : 'text',
        'required': True,
    }))

class AktivitasForm(forms.Form):
    Aktivitas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Masukkan kegiatan baru',
        'type' : 'text',
        'required': True,
    })) 

story6/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Participant as orang
from .models import Activity as kegiatan
from .forms import PesertaForm
from .forms import AktivitasForm

template="story6.html"

# Create your views here.
def Join1(request):
    if request.method == "POST":
        form = PesertaForm(request.POST)
        if form.is_valid():
            infoOrang = orang()
            infoOrang.Peserta = form.cleaned_data['Peserta']
            infoOrang.save()
        return redirect('/')
    else:
        infoOrang = orang.objects.all()
        form = PesertaForm()
        response = {"kuliah":infoOrang, 'form' : form}
        return render(request,template,response)

def Join2(request):
    if request.method == "POST":
        form = AktivitasForm(request.POST)
        if form.is_valid():
            infoKegiatan = kegiatan()
            infoKegiatan.Aktivitas = form.cleaned_data['Aktivitas']
            infoKegiatan.save()
        return redirect('/')
    else:
        infoKegiatan = kegiatan.objects.all()
        form = AktivitasForm()
        response = {"infoKegiatan":infoKegiatan, 'form' : form}
        return render(request,template,response)

def dynamic_lookup_view(request, my_id):
    if request.method == "POST":
        form = PesertaForm(request.POST)
        if form.is_valid():
            infoOrang = orang()
            infoOrang.Peserta = form.cleaned_data['Peserta']
            infoOrang.save()
        return redirect('/')
    else:
        obj=kegiatan.objects.get(id=my_id)
        form = PesertaForm()
        context = {"object":obj, "form": form}
        return render(request, 'daftarhadir.html', context)

story6/templates/daftarhadir.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Daftar Peserta</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">        
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col">
                    <form action="" method="POST">{% csrf_token %}
                        {{ form }}
                        <div class="centre-items">
                            <input type="submit" class="btn btn-primary" value="Tambahkan Peserta">
                        </div>
                    </form>
                </div>
                <div class="col">                       
                    {% for orang in infoOrang %}
                                <tr>
                                    <td>{{orang.Peserta}}</td>
                                </tr>
                            {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>

story6/templates/story6.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Form Kegiatan</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">        
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col">
                    <form action="" method="POST">{% csrf_token %}
                        {{ form }}
                        <div class="centre-items">
                            <input type="submit" class="btn btn-primary" value="Tambahkan Kegiatan">
                        </div>
                    </form>
                </div>
                <div class="col">                       
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">Kegiatan</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for kegiatan in infoKegiatan %}
                                <tr>
                                <th scope="row">
                                <a href="{% url 'story6:daftar' my_id=kegiatan.pk %}">{{ kegiatan.Aktivitas }}</a>
                                </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            
                </div>
            </div>
        </div>
    </body>
</html>